# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            ILA SJC Resource Guide
tagline:          Idaho Library Association's Social Justice Committee
description:      "Resources to help improve Idaho communities, compiled by the Idaho Library Association's Social Justice Committee."
locale:           en_US
timezone: America/Boise
lifespan:         2017
url:              https://ilasjc.github.io/ # use `/` when building for localhost
baseurl:          https://ilasjc.github.io/ # use `/` when building for localhost

author:
  name:           "Idaho Library Association's Social Justice Committee"
  url:            https://twitter.com/

paginate:         5
markdown:         kramdown  

kramdown: 
  auto_ids: true
  input: GFM
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
     default_lang: html

# Custom vars
version:          1.0.1

github:
  repository:           "ilasjc.github.io/"
